### ISSUE TITLE
When new cheeps is written to .csv file ends up on the same line as the previous cheep.

### ISSUE THREAD

**Issue by Joha6210** [ITU-BDSA2024-GROUP12/Chirp#22]
When new cheeps is written to .csv file ends up on the same line as the previous cheep.

![image](https://github.com/user-attachments/assets/8bc5b9a5-756b-47d4-84b1-4e06fd3b5148)

**Comment by PeterB441** [comment]
This was fixed a while ago. The csv-file was missing a newline character.
