### ISSUE TITLE
Double reference to an author in a cheep in DataModel.cs

### ISSUE THREAD

**Issue by Joha6210** [ITU-BDSA2024-GROUP12/Chirp#66]
Both ´AuthorId´ and ´Author´ tracks the author of a given cheep, which causes the following error:

_"The instance of entity type `'Author'` cannot be tracked because another instance with the same key value for `{'AuthorId'}` is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached."_

Temporary workaround: Only instantiate a cheep with either `AuthorId` or `Author` object

Permenant fix: Remove either `AuthorId` or `Author` object from the Cheep object in the datamodel
(I am rooting for removing `'Author'`

**Comment by R03SMUS** [comment]
Just a headsup, the DBInitializer.cs file, which seeds the database has both Author and AuthorId, removing 1 would mean manually adjusting 600 lines.

![Image](https://github.com/user-attachments/assets/5e35c177-9b09-4039-a72e-e9bd750aa7e4)

**Comment by MathiasJohneck** [comment]
This turned out to not be a real issue as it's not stored double in the actual database.
