### ISSUE TITLE
As a developer, i would like to add tests to our login functionality

### ISSUE THREAD

**Issue by ckmolusson** [ITU-BDSA2024-GROUP12/Chirp#74]
# Login testing
1.a)
I want to test the functionality of our ASP.NET Core Identity user login method and our Github Oauth login method

* Test ASP .NET Core Identity
* Test Github OAuth authentication

**Comment by MathiasJohneck** [comment]
As this is primarily identity, it makes little sense for us to test it in depth more than the UI elements and user experience which is done via. UI tests.
