### ISSUE TITLE
As an user, I would like to be able to send cheeps

### ISSUE THREAD

**Issue by Joha6210** [ITU-BDSA2024-GROUP12/Chirp#80]
# UI for sending Cheeps

1.a)

* Only authenticated users should be able to send cheeps
* Input field should be displayed under the second level headline `<h2` ("Public Timeline" or "<UserName> Timeline")
* New Cheep should appear on the public timeline and on the timeline of the user

**Comment by MathiasJohneck** [comment]
Constrain cheeps so that only cheeps of length 160 characters are considered valid. Should not accept cheeps of longer length
